esphealth/ESP/urls.py
'''
URLs for entire ESP Health django project

'''
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.conf.urls.defaults import include
from django.conf.urls.defaults import handler404
from django.conf.urls.defaults import handler500
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.forms import AuthenticationForm

from ESP.settings import MEDIA_ROOT, MEDIA_URL
#from ESP.esp.views import index, esplogin
from ESP.ui.views import status_page
from ESP.ui.views_survey import  generate_survey_report, view_survey_report, survey_import


admin.autodiscover()

urlpatterns = patterns('',
    
    # Core Application
    url(r'^$', status_page, name='status'),
    
    # Vaers
    url(r'^vaers/', include('ESP.vaers.urls')),
    
    # Survey 
    url(r'^survey_import/', survey_import, name='survey_import'),
    url(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    url(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Syndromic Surveillance
    url(r'^ss/', include('ESP.ss.urls')),

    # Login and Logout
    url(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    
    # About
    url(r'^about/', direct_to_template, {
        'template': 'about.html',
        'extra_context': {'title': 'About ESP'}
        }, name='about'),
    
    
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),
#    (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    
    # Configuration
    url(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #url(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    url(r'^util/', include('ESP.ui.urls')),
    
    # qmetric
    url(r'^qmetric/', include('ESP.qmetric.urls')),
    
    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #url(r'^codes', code_maintenance),
    #url(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #url(r'^/$', include('ESP.ui.urls')),
)

esphealth/ESP/vaers/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import url, patterns
from django.conf.urls.defaults import include

from ESP.vaers import views


urlpatterns = patterns(
    '',
    (r'^$', views.index),
    (r'^casetable$', views.list_cases),
    (r'^notify/(?P<id>\d+)/$', views.notify),
    (r'^report$', views.report),

    # Vaccine and Manufacturer Mapping
    url(r'^vaccines/', include('ESP.vaers.vaccine.urls')),
    
    # ptype can be digest or case.  digest takes a digest value for id, case takes a questionnaire id for id.
    url(r'^(?P<ptype>case|digest)/(?P<id>\w*)/$', views.case_details, name='present_case'),

    #line listing report
    url(r'^download/', views.download_vae_listing, name='download_listing'),    

)


esphealth/ESP/ui/forms.py
'''
                              ESP Health Project
                         Notifiable Diseases Framework
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms
from django.forms.util import ErrorList
from django.forms.models import modelformset_factory
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from ESP.nodis.models import STATUS_CHOICES
from ESP.nodis.base import DiseaseDefinition #Condition
from ESP.hef.base import AbstractLabTest
from ESP.static.models import Loinc
from ESP.vaers.heuristics import VaersLxHeuristic




class CaseStatusForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    status = forms.ChoiceField(STATUS_CHOICES[:4], required=False)
    comment = forms.CharField(widget=forms.Textarea, required=False)


class CodeMapForm(forms.Form):
    # fake instanciation to get the labs in the drop down
    vaerslabs = VaersLxHeuristic('wbc',None,None,None)
    TEST_CHOICES = [(name, name) for name in AbstractLabTest.get_all_names()]
    # FIXING MULTIPLE BILIRUBINS IN LIST 
    for name in vaerslabs.get_all_names():
        if (name,name) not in TEST_CHOICES:
            TEST_CHOICES.append((name, name))
    
    TEST_CHOICES.sort()
    test_name = forms.ChoiceField(choices=TEST_CHOICES, required=True)
    threshold = forms.FloatField(required=False)
    notes = forms.CharField(widget=forms.Textarea, required=False)
    output_code = forms.CharField(max_length=100, required=False)

class ConditionForm(forms.Form):
    #condition = forms.ChoiceField(choices=DiseaseDefinition.get_all_condition_choices())
    #old code 
    #Condition.condition_choices(wildcard=True))
    pass

class ReferenceCaseForm(forms.Form):
    notes = forms.CharField(required=False, widget=forms.Textarea)
    ignore = forms.BooleanField(required=False)

esphealth/ESP/templates/esp/case_define_detail.html
{% extends "espbase.html" %}
{% load esplib %}

{% block content %}

<h2><a href="javascript:history.go(-1)">Go Back</a></h2>
<br>


<center>

<h2>
<font color="RED">*Warning*: Up to 10K records can be downloaded to Excel, if you need more records, Please email</font>
<br><br><br>
<font color="#800000">Information for your selection</font></h2>
</center>
<br>


{% if lxs %}

<table border=1 cellspacing = "2" cellpadding = "3">
<tr>

  <th> Component Name <br><font color="BLUE">(Click to download all patients to Excel)</font></th>
  <th> CPT</th>
  <th> Component</th>
  <th> Non Numeric Results</th>
  <th> Min Numeric Result</th>
  <th> Max Numeric Result</th>
  <th> Reference Low || High</th>
  <th> Total # of Lx </th>
</tr>
   {% for lx in lxs %}
     <tr class="{% cycle row1,row2 %}">
       <td ><b><a href="{{SITEROOT}}/cases/define/download/{{lx.1}}/{{lx.2}}/">{{lx.0}}</a></b></td>
       <td><b>{{lx.1}}</b></td>
       <td><b>{{lx.2}}</b></td>
       <td><b><pre>{{lx.3}}</pre></b></td>
       <td><b><pre>{{lx.4}}</pre></b></td>
       <td><b><pre>{{lx.5}}</pre></b></td>
       <td><b><pre>{{lx.6}}</pre></b></td>
       <td align="right"><b>{{lx.7}}</b></td>
     </tr>

      {% endfor %}

    </table>
{% else %}
     <p>
      <h1>No matched records to show</h1>
     </p>
</div>
{% endif %}
{% endblock%}

esphealth/ESP/templates/esp/case_list.html
{% extends "espbase.html" %}
{% load esplib %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
{% endblock %}

{% block extrascript %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#case_table').flexigrid({
                striped: true,
                height: 'auto',
                url: '{% url json_case_grid %}{{ status }}/',
                dataType: 'json',
                singleSelect: true,
                {% if perms.esp.view_phi %}
                    colModel: [
                        {display: 'Case ID #', name: 'id', width: 50, sortable: true, align: 'left'},
                        {display: 'Condition', name: 'condition', width: 100, sortable: true, align: 'left'},
                        {display: 'Date', name: 'date_ordered', width: 75, sortable: true, align: 'left'},
                        {display: 'Provider Site', name: 'site', width: 150, sortable: true, align: 'left'},
                        {# Begin PHI #}
                        {display: 'Patient Name', name: 'name', width: 150, sortable: true, align: 'left'},
                        {display: 'MRN', name: 'mrn', width: 50, sortable: true, align: 'left'},
                        {display: 'Patient Address', name: 'address', width: 150, sortable: true, align: 'left'},
                        {# End PHI #}
                        {display: 'Workflow State', name: 'workflow', width: 100, sortable: true, align: 'left'},
                        {display: 'Last Updated', name: 'last_updated', width: 75, sortable: true, align: 'left'},
                        {display: 'Previously Notified Cases', name: 'prev_cases', width: 100, sortable: true, align: 'left'},
                        ],
                    searchitems: [
                        {display: 'Condition', name: 'condition'},
                        {# Begin PHI #}
                        {display: 'Patient Last Name', name: 'name'},
                        {display: 'Medical Record #', name: 'mrn'},
                        {# End PHI #}
                        ],
                {% else %}
                    colModel: [
                        {display: 'Case ID #', name: 'id', width: 50, sortable: true, align: 'left'},
                        {display: 'Condition', name: 'condition', width: 100, sortable: true, align: 'left'},
                        {display: 'Date', name: 'date_ordered', width: 100, sortable: true, align: 'left'},
                        {display: 'Provider Site', name: 'site', width: 200, sortable: true, align: 'left'},
                        {display: 'Workflow State', name: 'workflow', width: 100, sortable: true, align: 'left'},
                        {display: 'Last Updated', name: 'last_updated', width: 100, sortable: true, align: 'left'},
                        {display: 'Previously Notified Cases', name: 'prev_cases', width: 100, sortable: true, align: 'left'},
                        ],
                    searchitems: [
                        {display: 'Condition', name: 'condition'},
                        ],
                {% endif %}
                sortname: 'id',
                sortorder: 'asc',
                usepager: 'true',
                width: '100%',
                rpOptions: [10, 25, 50, 100],
                rp: {{ default_rp }},
                showToggleBtn: false,
            });
        });
    </script>
{% endblock %}

{% block content %}


<table id="case_table">
</table>


{% endblock%}

esphealth/ESP/templates/esp/conditiondrugnamemap.html
{% extends "espbase.html" %}

{% block content %}

<h2><a href="javascript:history.go(-1)">Go Back</a></h2>

<center>
<h2><font color="#800000">Condition-Drug Name Map</font></h2>
</center>
<br>
{% if msg %}
     <br><br>
     <center>
     <h3><font color="blue"> {{msg}}</font></h3>
      </center> 
{% endif %}




{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{{SITEROOT}}/preload/conditiondrugname/update/" method="post">
<center>
<input type="submit" name="submit" value="Save into a file" >
</center>
<br>
<table cellspacing="10" cellpadding="3" border="1" width="95%">
<tr class="{% cycle row1,row2 as rowcolors %}">
  <th>Id</th>
  <th>Rule</th>
  <th>DrugName</th>
  <th>Route</th>
  <th>Used in definition?</th>
  <th>Used in HL7? </th>
</tr>
 {% for mapobj in maps %} 
     <tr class="{% cycle rowcolors %}">
      <td width="15%"> {{ mapobj.id }}<input type="hidden" name="ID_{{ mapobj.id }}" value={{ mapobj.id }}></td>
      <td width="25%"> 
	     <SELECT name="RULE_{{ mapobj.id }}">
        {% for thisr in rules %}
           {% ifequal mapobj.CondiRule.ruleName thisr.ruleName %} <OPTION value="{{thisr.ruleName}}" SELECTED> {{thisr.ruleName}}</OPTION> {% endifequal %}
           {% ifnotequal mapobj.CondiRule.ruleName thisr.ruleName %} <OPTION value="{{thisr.ruleName}}"> {{thisr.ruleName}}</OPTION> {% endifnotequal %}
         {% endfor %}
         </SELECT>
      </td>

      <td width="20%"> <input type="text" name="NDC_{{ mapobj.id }}" size="15" value="{{ mapobj.CondiDrugName}}"> </td>
      <td width="15%"> <input type="text" name="ROUTE_{{ mapobj.id }}" size="15" value={{ mapobj.CondiDrugRoute}}> </td>
      <td width="20%"> <input type="text" name="DEFINE_{{ mapobj.id }}" size="15" value={{mapobj.CondiDefine}} ></td>
      <td width="20%"> <input type="text" name="SEND_{{ mapobj.id }}" size="15" value={{mapobj.CondiSend}} ></td>
      </tr>

    {% endfor %}
 {% for i in newrec %}
     <tr class="{% cycle rowcolors %}">
      <td width="15%"> Add New <input type="hidden" name="ID_NEW{{ i }}" value="NEW{{i}}"></td>
      <td width="25%">
       <SELECT name="RULE_NEW{{ i }}">
        {% for thisr in rules %}
           <OPTION value="{{thisr.ruleName}}"> {{thisr.ruleName}}</OPTION> 
         {% endfor %}
       </SELECT>
      </td>
      <td width="20%"> <input type="text" name="NDC_NEW{{i}}" size="50" > </td>
      <td width="15%"> <input type="text" name="ROUTE_NEW{{i}}" size="50" > </td>
      <td width="20%"> <input type="text" name="DEFINE_NEW{{ i}}" size="15" value='0'></td>
      <td width="20%"> <input type="text" name="SEND_NEW{{ i}}" size="15" value='1'></td>
      </tr>

    {% endfor %}
  
</table>
<br>
<center>
<input type="submit" name="submit" value="Save into a file" >
</center>
</form>


{% endblock %}

esphealth/ESP/templates/esp/conditiondx_codemap.html
{% extends "espbase.html" %}

{% block content %}

<h2><a href="javascript:history.go(-1)">Go Back</a></h2>

<center>
<h2><font color="#800000">Condition-dx code Map</font></h2>
</center>
<br>
{% if msg %}
     <br><br>
     <center>
     <h3><font color="blue"> {{msg}}</font></h3>
      </center> 
{% endif %}




{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{{SITEROOT}}/preload/conditiondx_code/update/" method="post">
<center>
<input type="submit" name="submit" value="Save into a file" >
</center>
<br>
<table cellspacing="10" cellpadding="3" border="1" width="95%">
<tr class="{% cycle row1,row2 as rowcolors %}">
  <th>Id</th>
  <th>Rule</th>
  <th>Dx code</th>
  <th>Used in definition?</th>
  <th>Used in HL7? </th>
</tr>
 {% for mapobj in maps %} 
     <tr class="{% cycle rowcolors %}">
      <td width="15%"> {{ mapobj.id }}<input type="hidden" name="ID_{{ mapobj.id }}" value={{ mapobj.id }}></td>
      <td width="25%"> 
	     <SELECT name="RULE_{{ mapobj.id }}">
        {% for thisr in rules %}
           {% ifequal mapobj.CondiRule.ruleName thisr.ruleName %} <OPTION value="{{thisr.ruleName}}" SELECTED> {{thisr.ruleName}}</OPTION> {% endifequal %}
           {% ifnotequal mapobj.CondiRule.ruleName thisr.ruleName %} <OPTION value="{{thisr.ruleName}}"> {{thisr.ruleName}}</OPTION> {% endifnotequal %}
         {% endfor %}
         </SELECT>
      </td>
      <td width="25%"> <input type="text" name="ICD_{{ mapobj.id }}" size="15" value={{ mapobj.CondiDx_code}}> </td>
      <td width="25%"> <input type="text" name="DEFINE_{{ mapobj.id }}" size="15" value={{mapobj.CondiDefine}} ></td>
      <td width="25%"> <input type="text" name="SEND_{{ mapobj.id }}" size="15" value={{mapobj.CondiSend}} ></td>
      </tr>

    {% endfor %}
 {% for i in newrec %}
     <tr class="{% cycle rowcolors %}">
      <td width="15%"> Add New <input type="hidden" name="ID_NEW{{ i }}" value="NEW{{i}}"></td>
      <td width="25%">
       <SELECT name="RULE_NEW{{ i }}">
        {% for thisr in rules %}
           <OPTION value="{{thisr.ruleName}}"> {{thisr.ruleName}}</OPTION> 
         {% endfor %}
       </SELECT>
      </td>
      <td width="25%"> <input type="text" name="ICD_NEW{{i}}" size="15" > </td>
      <td width="25%"> <input type="text" name="DEFINE_NEW{{ i}}" size="15" value='0'></td>
      <td width="25%"> <input type="text" name="SEND_NEW{{ i}}" size="15" value='1'></td>
      </tr>

    {% endfor %}
  
</table>
<br>
<center>
<input type="submit" name="submit" value="Save into a file" >
</center>
</form>


{% endblock %}

esphealth/ESP/templates/esp/conditionloincmap.html
{% extends "espbase.html" %}

{% block content %}

<h2><a href="javascript:history.go(-1)">Go Back</a></h2>
<center>
<h2><font color="#800000">Condition-Loinc Map</font></h2>
</center>
<br>

{% if msg %}
     <br><br>
     <center>
     <h3><font color="blue"> {{msg}}</font></h3>
      </center> 
{% endif %}




{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{{SITEROOT}}/preload/conditionloinc/update/" method="post">
<center>
<input type="submit" name="submit" value="Save into a file" >
</center>
<br>
<table cellspacing="10" cellpadding="3" border="1" width="95%">
<tr class="{% cycle row1,row2 as rowcolors %}">
  <th>Id</th>
  <th>Rule</th>
  <th>Loinc</th>
  <th>Operator</th>
  <th>Value</th>
  <th>SNOMED - Positive</th>
  <th>SNOMED - Negative</th>
  <th>SNOMED - Indeterminate</th>
  <th>Used in definition?</th>
  <th>Used in HL7? </th>
</tr>
 {% for mapobj in maps %} 
     <tr class="{% cycle rowcolors %}">
      <td width="10%"> {{ mapobj.id }}<input type="hidden" name="ID_{{ mapobj.id }}" value={{ mapobj.id }}></td>
      <td width="18%"> 
	     <SELECT name="RULE_{{ mapobj.id }}">
        {% for thisr in rules %}
           {% ifequal mapobj.CondiRule.ruleName thisr.ruleName %} <OPTION value="{{thisr.ruleName}}" SELECTED> {{thisr.ruleName}}</OPTION> {% endifequal %}
           {% ifnotequal mapobj.CondiRule.ruleName thisr.ruleName %} <OPTION value="{{thisr.ruleName}}"> {{thisr.ruleName}}</OPTION> {% endifnotequal %}
         {% endfor %}
         </SELECT>
      </td>
      <td width="15%"> <input type="text" name="LOINC_{{ mapobj.id }}" size="15" value={{ mapobj.CondiLOINC}}> </td>

      <td width="15%"> 
           {% ifequal mapobj.CondiOperator ">" %} <input type="text" name="OPE_{{ mapobj.id }}" size="15" value="&gt;"> {%endifequal%}      
          {% ifnotequal mapobj.CondiOperator ">" %} <input type="text" name="OPE_{{ mapobj.id }}" size="15" value={{ mapobj.CondiOperator}}> {%endifnotequal%}

       </td>
      <td width="15%"> <input type="text" name="VALUE_{{ mapobj.id }}" size="15" value={{ mapobj.CondiValue}}> </td>
      <td width="15%"> <input type="text" name="SNMDPOSI_{{ mapobj.id }}" size="15" value={{ mapobj.CondiSNMDPosi}}> </td>
      <td width="15%"> <input type="text" name="SNMDNEGA_{{ mapobj.id }}" size="15" value={{ mapobj.CondiSNMDNega}}> </td>
      <td width="15%"> <input type="text" name="SNMDINDE_{{ mapobj.id }}" size="15" value={{ mapobj.CondiSNMDInde}}> </td>
      <td width="5%"> <input type="text" name="DEFINE_{{ mapobj.id }}" size="15" value={{mapobj.CondiDefine}} ></td>
      <td width="5%"> <input type="text" name="SEND_{{ mapobj.id }}" size="15" value={{mapobj.CondiSend}} ></td>
      </tr>

    {% endfor %}
 {% for i in newrec %}
     <tr  class="{% cycle rowcolors %}">
      <td width="10%"> Add New <input type="hidden" name="ID_NEW{{ i }}" value="NEW{{i}}"></td>
      <td width="18%">
       <SELECT name="RULE_NEW{{ i }}">
        {% for thisr in rules %}
           <OPTION value="{{thisr.ruleName}}"> {{thisr.ruleName}}</OPTION> 
         {% endfor %}
       </SELECT>
      </td>
      <td width="15%"> <input type="text" name="LOINC_NEW{{i}}" size="15" > </td>
      <td width="15%"> <input type="text" name="OPE_NEW{{i}}" size="15" value='contain'> </td>
      <td width="15%"> <input type="text" name="VALUE_NEW{{i}}" size="15" value='POSITIV,DETECT'> </td>
      <td width="15%"> <input type="text" name="SNMDPOSI_NEW{{i}}" size="15" > </td>
      <td width="15%"> <input type="text" name="SNMDNEGA_NEW{{i}}" size="15" > </td>
      <td width="15%"> <input type="text" name="SNMDINDE_NEW{{i}}" size="15" > </td>
      <td width="5%"> <input type="text" name="DEFINE_NEW{{ i}}" size="15" value='1'></td>
      <td width="5%"> <input type="text" name="SEND_NEW{{ i}}" size="15" value='1'></td>
      </tr>

    {% endfor %}
  
</table>
<br>
<center>
<input type="submit" name="submit" value="Save into a file" >
</center>
</form>


{% endblock %}

esphealth/ESP/templates/esp/edit_ext_loinc_map.html
{% extends 'esp/espbase.html' %}
{% load i18n %}

{% block extrascript %}
<script type="text/javascript">

  function disable_code_fields() {
  $('#id_ext_code').attr('disabled', true);
  $('#id_ext_name').attr('disabled', true);
  $('#id_notes').attr('disabled', true);
  };
  
  function enable_code_fields() {
  $('#id_ext_code').removeAttr('disabled');
  $('#id_ext_name').removeAttr('disabled');
  $('#id_notes').removeAttr('disabled');
  };

  $(document).ready( function() {
  $('#loinc_lookup')
  .click( function() {
  var loinc_num = $('#id_loinc_num').val();
  if ( loinc_num ) {
  $('#loinc_name').load('{% url loinc_name_lookup %}', {loinc_num: loinc_num}, function(responseText, textStatus) {
  if ( textStatus == 'success' ) {
  $('.blurb').hide();
  $('#blurb_found').show();
  enable_code_fields();
  $('#id_ext_code').focus();
  } else {
  $('.blurb').hide();
  $('#blurb_not_found').show();
  disable_code_fields();
  };
  });
  } else {
  $('.blurb').hide();
  $('#blurb_enter_number').show();
  disable_code_fields();
  };
  return false;
  })
  .blur( function() {
  this.click();
  })
  .click()
  ;
  $('#cancel_button').click( function() {
  location.href = "{% url show_ext_loinc_maps %}";
  });
  $('#id_loinc_num').focus();
  });
</script>
{% endblock %}



{% block content %}

<h1>
    External Code to LOINC Mapping
</h1>

<p>
    <span class="blurb" id="blurb_enter_number">{% trans 'Enter a LOINC number and click "Lookup".' %}</span>
    <span class="blurb" id="blurb_not_found">{% trans 'LOINC number not found in database' %}</span>
    <span class="blurb" id="blurb_found">{% trans 'Valid LOINC number found.  Enter external code information.' %}</span>
</p>

<form method="POST">
    <table>
        <tr>
            <th>
                <label for="id_loinc_num">LOINC Number </label>: 
            </th>
            <td>
                {{ form.loinc_num }}
                {{ form.loinc_num.errors }}
                <input type="button" id="loinc_lookup" value="{% trans 'Lookup LOINC Number' %}" />
            </td>
        </tr>
        <tr>
            <th>
                <label for="id_ext_code">LOINC Name</label>: 
            </th>
            <td>
                <span id='loinc_name'></span>
            </td>
        </tr>
        <tr>
            <th>
                <label for="id_ext_code">External Code Number</label>: 
            </th>
            <td>
                {{ form.ext_code }}
                {{ form.ext_code.errors }}
            </td>
        </tr>
        <tr>
            <th>
                <label for="id_ext_name">External Code Name</label>: 
            </th>
            <td>
                {{ form.ext_name }}
                {{ form.ext_name.errors }}
            </td>
        </tr>
        <tr>
            <th>
                <label for="id_notes">Notes</label>: 
            </th>
            <td>
                {{ form.notes }}
                {{ form.notes.errors }}
            </td>
        </tr>
    </table>
    <p>
        <input type='button' id="cancel_button" value="{% trans 'Cancel' %}" />
        <input type='submit' action='{{ form_action }}' method='POST' value="{% trans 'Save' %}"/>
</form>


{% endblock %} {# content #}

esphealth/ESP/templates/esp/rule_detail.html
{% extends "espbase.html" %}

{% block content %}

<h2><a href="javascript:history.go(-1)">Go Back</a></h2>

{% if rule %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<table cellspacing="10" cellpadding="3" border="1" width="100%">
<tr><td colspan = "2" align = "center" bgcolor="#800000"><font size="+1" color="lightyellow">Case Definition Rule Details</font></td></tr>
 <tr class="{% cycle row1,row2 as rowcolors %}">
 <td width="30%">Rule Internal ID</td><td>{{rule.id}}</td></tr>
 
 <tr class="{% cycle rowcolors %}">
 <td width="30%">Name</td><td>{{rule.ruleName}}</td></tr>

 <tr class="{% cycle rowcolors %}">
 <td width="30%">SQL query</td><td>{{rule.ruleSQL}}</td></tr>

 <tr class="{% cycle rowcolors %}">
 <td width="30%">Comments</td><td>{{rule.ruleComments}}</td></tr>

 <tr class="{% cycle rowcolors %}">
 <td width="30%">Message Format</td><td>{{rule.ruleMsgFormat}}</td></tr>

 <tr class="{% cycle rowcolors %}">
 <td width="30%">Message Destination</td><td>{{rule.ruleMsgDest}}</td></tr>
</table>

{% else %}
    <p>No Rule record available.</p>
{% endif %}
{% endblock %}