esphealth/ESP/ui/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2010 Channing Laboratory
@license: LGPL
'''


from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.conf.urls.defaults import include
from django.conf.urls.defaults import handler404
from django.conf.urls.defaults import handler500
from django.contrib import admin

from ESP.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = patterns('ESP.ui.views',
    url(r'^labtest/lookup/$', 'labtest_lookup', name='labtest_lookup'),
    url(r'^labtest/detail/$', 'labtest_detail', name='labtest_detail'),
    url(r'^labtest/linelist/(?P<native_code>.*)$', 'labtest_csv', name='labtest_csv'),
    url(r'^labtest/linelist/(?P<native_code>.*)$', 'labtest_csv', name='labtest_csv'),
    url(r'^labtest/ignore_set/$', 'ignore_code_set', name='ignore_code_set'),
    url(r'^labtest/map/(?P<native_code>.+)/$', 'map_native_code', name='map_native_code'),
    url(r'^labtest/unmapped/$', 'unmapped_labs_report', name='unmapped_labs_report'),
    #
    #-------------------------------------------------------------------------------
    # Nodis
    #-------------------------------------------------------------------------------
    #
    url(r'^cases/$', 'case_list', {'status': 'all'}, name='nodis_cases_all'),
    url(r'^cases/list/awaiting_review/$', 'case_list', {'status': 'await'}, name='nodis_cases_awaiting_review'),
    url(r'^cases/list/under_review/$', 'case_list', {'status': 'under'}, name='nodis_cases_under_review'),
    url(r'^cases/list/queued/$', 'case_list', {'status': 'queued'}, name='nodis_cases_queued'),
    url(r'^cases/list/sent/$', 'case_list', {'status': 'sent'}, name='nodis_cases_sent'),
    #
    # Case Detail
    #
    url(r'^cases/view/(?P<case_id>\d+)/$', 'case_detail', name='nodis_case_detail'),
    url(r'^cases/viewpert/(?P<case_id>\d+)/$', 'pertussis_detail', name='nodis_pertussis_detail'),
    url(r'^cases/update/(?P<case_id>\d+)/$', 'case_status_update', name='nodis_case_update'),
    url(r'^cases/transmit/(?P<case_id>\d+)/$', 'case_queue_for_transmit', name='nodis_case_transmit'),
    url(r'^provider/(?P<provider_id>\w+)/$', 'provider_detail', name='provider_detail'),
    url(r'^patient/(?P<patient_pk>\d+)/records/$', 'all_records', name='all_records'),
    #
    # Validator
    #
    url(r'^validate/$', 'validator_summary', name='validator_summary'),
    url(r'^validate/missing/$', 'validate_missing', name='validate_missing'),
    url(r'^validate/missing/case/(?P<result_id>\d+)/$', 'missing_case_detail', name='missing_case_detail'),
    url(r'^validate/new/$', 'validate_new', name='validate_new'),
    url(r'^validate/similar/$', 'validate_similar', name='validate_similar'),
    url(r'^validate/exact/$', 'validate_exact', name='validate_exact'),

)

esphealth/ESP/urls.py
'''
URLs for entire ESP Health django project

'''
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.conf.urls.defaults import include
from django.conf.urls.defaults import handler404
from django.conf.urls.defaults import handler500
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.forms import AuthenticationForm

from ESP.settings import MEDIA_ROOT, MEDIA_URL
#from ESP.esp.views import index, esplogin
from ESP.ui.views import status_page
from ESP.ui.views_survey import  generate_survey_report, view_survey_report, survey_import


admin.autodiscover()

urlpatterns = patterns('',
    
    # Core Application
    url(r'^$', status_page, name='status'),
    
    # Vaers
    url(r'^vaers/', include('ESP.vaers.urls')),
    
    # Survey 
    url(r'^survey_import/', survey_import, name='survey_import'),
    url(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    url(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Syndromic Surveillance
    url(r'^ss/', include('ESP.ss.urls')),

    # Login and Logout
    url(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    
    # About
    url(r'^about/', direct_to_template, {
        'template': 'about.html',
        'extra_context': {'title': 'About ESP'}
        }, name='about'),
    
    
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),
#    (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    
    # Configuration
    url(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #url(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    url(r'^util/', include('ESP.ui.urls')),
    
    # qmetric
    url(r'^qmetric/', include('ESP.qmetric.urls')),
    
    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #url(r'^codes', code_maintenance),
    #url(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #url(r'^/$', include('ESP.ui.urls')),
)

esphealth/ESP/vaers/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import url, patterns
from django.conf.urls.defaults import include

from ESP.vaers import views


urlpatterns = patterns(
    '',
    (r'^$', views.index),
    (r'^casetable$', views.list_cases),
    (r'^notify/(?P<id>\d+)/$', views.notify),
    (r'^report$', views.report),

    # Vaccine and Manufacturer Mapping
    url(r'^vaccines/', include('ESP.vaers.vaccine.urls')),
    
    # ptype can be digest or case.  digest takes a digest value for id, case takes a questionnaire id for id.
    url(r'^(?P<ptype>case|digest)/(?P<id>\w*)/$', views.case_details, name='present_case'),

    #line listing report
    url(r'^download/', views.download_vae_listing, name='download_listing'),    

)


esphealth/ESP/ui/forms.py
'''
                              ESP Health Project
                         Notifiable Diseases Framework
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms
from django.forms.util import ErrorList
from django.forms.models import modelformset_factory
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from ESP.nodis.models import STATUS_CHOICES
from ESP.nodis.base import DiseaseDefinition #Condition
from ESP.hef.base import AbstractLabTest
from ESP.static.models import Loinc
from ESP.vaers.heuristics import VaersLxHeuristic




class CaseStatusForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    status = forms.ChoiceField(STATUS_CHOICES[:4], required=False)
    comment = forms.CharField(widget=forms.Textarea, required=False)


class CodeMapForm(forms.Form):
    # fake instanciation to get the labs in the drop down
    vaerslabs = VaersLxHeuristic('wbc',None,None,None)
    TEST_CHOICES = [(name, name) for name in AbstractLabTest.get_all_names()]
    # FIXING MULTIPLE BILIRUBINS IN LIST 
    for name in vaerslabs.get_all_names():
        if (name,name) not in TEST_CHOICES:
            TEST_CHOICES.append((name, name))
    
    TEST_CHOICES.sort()
    test_name = forms.ChoiceField(choices=TEST_CHOICES, required=True)
    threshold = forms.FloatField(required=False)
    notes = forms.CharField(widget=forms.Textarea, required=False)
    output_code = forms.CharField(max_length=100, required=False)

class ConditionForm(forms.Form):
    #condition = forms.ChoiceField(choices=DiseaseDefinition.get_all_condition_choices())
    #old code 
    #Condition.condition_choices(wildcard=True))
    pass

class ReferenceCaseForm(forms.Form):
    notes = forms.CharField(required=False, widget=forms.Textarea)
    ignore = forms.BooleanField(required=False)

esphealth/ESP/templates/ui/case_list.html
{% extends "base.html" %}
{% load url from future %} {# https://docs.djangoproject.com/en/dev/releases/1.3/#changes-to-url-and-ssi #}
{% load templatefilters %}

{% block extrascript %}
    
    <script type="text/javascript" src="{{ site_javascript_folder }}dropdown-check-list.1.1/js/ui.dropdownchecklist-1.1-min.js"></script>
    <link type="text/css" rel="stylesheet" media="screen" href="{{ site_javascript_folder }}dropdown-check-list.1.1/css/ui.dropdownchecklist.standalone.css" />


    <script type="text/javascript">
        $(document).ready(function() {
            $.datepicker.setDefaults({
                changeMonth: true,
                changeYear: true,
            });
            $('#id_date_after').datepicker();
            $('#id_date_before').datepicker();
            $('#id_status').dropdownchecklist({ width: 300, emptyText: "Select..." });
            $('#id_condition').dropdownchecklist({ width: 300, emptyText: "Select..." });
            $('#id_provider_dept').dropdownchecklist({ width: 300, maxDropHeight: 350, emptyText: "Select..." });
        });
    </script>
{% endblock %}

{% block extrastyle %}

<style type="text/css" media="all"> 
    form ol {
        list-style: none;
    }
    #search_div {
        float: left;
    }
    #summary_div {
        float: right;
    }
    #form_table {
        border: 0;
    }
    #form_table th {
        text-align: right;
        border: 0;
    }
    #form_table td {
        text-align: left;
        border: 0;
    }
</style>

{% endblock %}

{% block content %}

<div id="search_div">
    <h2>Filter</h2>
    <form id="search_form" method="GET" action="{% url 'nodis_cases_all' %}">
        <table id="form_table">
            {{ search_form.as_table }}
        </table>
        <p>
            <input type="submit" value="Update Results" />
            <a href="{{ clear_search_path }}">Reset Filter</a>
        <p>
            <a href="{{ full_path }}&export_csv=case_list">Export case list to CSV file</a>
        <p>
    </form>
</div>

<div style="clear:both;" />

<h2>Cases by Patient</h2>

<table id="case_patient_table">
    <tr>
        <th>&nbsp;</th>
        {% for column in table.columns %}
            {% if column.sortable %}
                <th><a href="{{ full_path }}&sort={{ column.name_toggled }}">{{ column }}</a></th>
            {% else %}
                <th>{{ column }}</th>
            {% endif %}
        {% endfor %}
    </tr>
    {% for row in page.object_list %}
        <tr>
    	{% with cond_url=row.condition|get_url  %}
        <td><a href="{% url cond_url row.id %}">view</a></td>
		{% endwith %}
        {% for value in row %}
            <td>{{ value }}</td>
        {% endfor %}
        </tr>
    {% endfor %}
</table>

<div class="pagination">
    <p>
    {{ page.paginator.count }} cases matching query.
    </p>
    <p>
    <span class="step-links">
        {% if page.has_previous %}
            <a href="{{ full_path }}&page={{ page.previous_page_number }}">previous</a> |
        {% endif %}


        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            | <a href="{{ full_path }}&page={{ page.next_page_number }}">next</a>
        {% endif %}
    </span>
    </p>
</div>



{% endblock%}

esphealth/ESP/templates/ui/labtest_detail.html
{% extends "base.html" %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
{% endblock %}

{% block content %}

<p>
    <em>Click test code to download CSV file.</em>
</p>

<table>
    <tr>
        <th>Native Code
        <th>Native Name(s)
        <th>Non-Numeric Results
        <th>Min Numeric Result
        <th>Max Numeric Result
        <th>Reference Low(s)
        <th>Reference High(s)
        <th>Result Count
    </tr>
    {% for test in details %}
    <tr>
        <td><a href="{% url labtest_csv test.native_code %}">{{ test.native_code }}</a>
        <td>{{ test.native_names|join:"<br>" }}
        <td>{{ test.result_strings|join:"<br>" }}
        <td>{{ test.min_result_float }}
        <td>{{ test.max_result_float }}
        <td>{{ test.ref_low_values|join:"<br>" }}
        <td>{{ test.ref_high_values|join:"<br>" }}
        <td>{{ test.count }}
    </tr>
    {% endfor %}
</table>

<p>
    <a href="{% url labtest_lookup %}">Back to Lab Test Lookup form</a>
</p>


{% endblock%}

esphealth/ESP/templates/ui/labtest_lookup.html
{% extends "base.html" %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
{% endblock %}

{% block content %}

<p>
<form id="lookup_form" action="{% url labtest_lookup %}" method="POST">
    <table>
        {{ lookup_form.as_p }}
    </table>
    <input type="submit" name="lookup" value="Search Tests" />
    {% csrf_token %}
</form>
</p>



{% if tests %}
<hr>
<h2>Results</h2>
<form id='native_codes' action='{% url labtest_detail %}' method='POST'>
    <input type="submit" name="detail" value="View Detail" />
    <table>
    {{ result_form }}
    </table>
</form>
{% endif %}

{% endblock%}

esphealth/ESP/templates/ui/map_native_code.html
{% extends 'base.html' %}

{% block extrastyle %}
    <style type="text/css">
    table {
        border-width: thin;
        border-spacing: 0;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: white;
    }
    table th {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    table td {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    </style>
{% endblock %}


{% block content %}

<div style="float:right;">

    <h2>Result Strings</h2>
    <blockquote>
        <p>10 most popular:
        <table>
            <tr>
                <th>Result
                <th>Lab Record Count
            </tr>
            {% for item in result_strings %}
            <tr>
                <td>{{ item.result_string }}
                <td>{{ item.count }}
            </tr>
            {% endfor %}
        </table>
    </blockquote>

    <h2>Reference High Values</h2>
    <p>
        Number of results <em>with</em> numeric result, but <em>without</em> 
        reference high: 
        <br>
        {{ without_ref_high }} ({{ without_ref_high_percent|floatformat:3 }}%).
    </p>
    <blockquote>
        <p>10 most popular:
        <table>
            <tr>
                <th>Reference High Value
                <th>Lab Record Count
            </tr>
            {% for item in ref_high_values %}
            <tr>
                <td>{{ item.ref_high_string }}
                <td>{{ item.count }}
            </tr>
            {% endfor %}
        </table>
    </blockquote>

</div>

<h2>Native Code</h2> 
<p>{{ native_code }}</p>

<h2>Native Names</h2> 
<p>{{ native_names|join:"<br>" }}</p>

<h2>Record Count</h2>
<p>
    {{ count }}
    <br>(Number of records in database with this native code)
</p>

<h2>Select an Abstract Lab</h2>
<form method="POST" action="{% url map_native_code native_code %}">
    {{ form.as_p }}
    <p>
        <input type="submit" value="Map It!">
        &nbsp;
        <a href="{% url unmapped_labs_report %}">cancel</a>
        &nbsp;
        <a href="{% url ignore_code native_code %}">ignore</a>
    </p>
    {% csrf_token %}
</form>

<hr>

<h2>Comment Values</h2>

<p>10 most popular:
<table>
    <tr>
        <th>Comment Value
        <th>Lab Record Count
    </tr>
    {% for item in comments %}
    <tr>
        <td>{{ item.comment }}
        <td>{{ item.count }}
    </tr>
    {% endfor %}
</table>

{% endblock %}

esphealth/ESP/templates/ui/status.html
{% extends 'base.html' %}


{% block content %}
<p>Date:  {{ today_string }}
<br>Site:  {{ site_name }}
<br>
<br>
{{ comment }}

<h2>
    <hr>
    Nodis
    <hr>
</h2>


<div id="all_case_summary" style="float:right;">
    <h3>
        All Cases:
    </h3>
    {% if all_case_summary.count %}
    <table id="new_case_summary_table">
        <tr>
            <th>Condition
            <th>Count
        {% for item in all_case_summary %}
        <tr>
            <td>{{ item.condition }}
            <td>{{ item.count }}
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>
        <em>No cases</em>
    </p>
    {% endif %}
</div>

<div id="new_case_summary" style="float: left;">
    <h3>
        New Cases Today: 
    </h3>
    {% if new_case_summary.count %}
    <table id="new_case_summary_table">
        <tr>
            <th>Condition
            <th>Count
        {% for item in new_case_summary %}
        <tr>
            <td>{{ item.condition }}
            <td>{{ item.count }}
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>
        <em>No new cases today</em>
    </p>
    {% endif %}
</div>

<p style="clear: left;">&nbsp;</p>

<div id="report_summary" style="float: left; clear: left;">

    <h3>
        Case Reports:
    </h3>

    <p>
        <em>Case reports transmitted in past day</em>
    </p>

    {% if reports %}
        <table id="case_reports">
            <tr>
                <th>Case ID
                <th>Condition
                <th>Case Date
                <th>Patient DB ID
                <th>Report Timestamp
                <th>Report Sent?
                <th>Report Filename
            {% for rep in reports %}
                {% for c in rep.cases.all %}
                <tr>
                    <td><a href="{% url nodis_case_detail c.pk %}">{{ c.pk }}</a>
                    <td>{{ c.condition }}
                    <td>{{ c.date }}
                    <td>{{ c.patient.pk }}
                    <td>{{ rep.timestamp }}
                    <td>{{ rep.sent }}
                    <td>{{ rep.filename }}
                {% endfor %}
            {% endfor %}
        </table>
    {% else %}
        <p>
            <em>No cases reported in past day</em>
        </p>
    {% endif %}
</div>



<div style="clear: both;" />

<p>&nbsp;</p>

<h2 style="clear: both;">
    <hr>
    Data Provenance
    <hr>
</h2>

<div id="provenance_summary" style="clear: both;">

    <p>
        <em>Data load summary for past day</em>
    </p>

    <table id="provenance_summary_table">
        <tr>
            <th>Status
            <th>Number of Files
        {% for i in data_status %}
        <tr>
            <td>{{ i.status }}
            <td>{{ i.count }}
        {% endfor %}
    </table>

</div>


<div id="provenance_detail" style="clear: both;">
    
    <p>
        <em>Data sources loaded in past day</em>
    </p>
    <table id="provenance_detail_table">
        <tr>
            <th>Source
            <th>Timestamp
            <th>Status
	    <th>Valid Record Count
            <th>Error Count
        </tr>
        {% for prov in provenances %}
        <tr>
            <td>{{ prov.source }}
            <td>{{ prov.timestamp }}
            <td>{{ prov.status }}
	    <td>{{ prov.valid_rec_count }}
	    <td>{{ prov.error_count }}
        </tr>
        {% endfor %}
    </table>

</div>

{% comment %}

<div id="unmapped_lab_summary">
    <h2>
        <hr>
        Unmapped Lab Tests
        </hr>
    </h2>
    <table>
        <tr>
            <th>Native Name</th>
            <th>Native Code</th>
            <th>Lab Record Count</th>
        </tr>
        {% for item in unmapped_labs %}
        <tr>
            <td>{{ item.native_name }}</td>
            <td>{{ item.native_code }}</td>
            <td>{{ item.count }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endcomment %}

{% endblock %}

esphealth/ESP/templates/ui/survey_report.html
{% extends 'base.html' %}


{% block content %}
<p>Date:  {{ today_string }}
<br>Site:  {{ site_name }}


<h2>
    <hr>
    {{ subtitle }}
    <hr>
</h2>

<p>
    <a href="{{ full_path }}&export_csv=brfssdemo_report">Export Survey Report to CSV file</a>
 <p>

{% for table in tables %}
<div id="new_case_summary" style="float: left;">
    <h3>
         {{ table.0 }}
    </h3>
    
    <table id="new_case_summary_table1">
    
    <tr>
     {% for item in table.1 %}
           <th> {{ item.name }}   </th>
            
         {% endfor %}
        {% for row in table.2 %}
         <tr> 
         
        {% for col in row %}
            {% if col %}
                <td> {{ col }} </td>
            {% else %}
                <td> </td>
            {% endif %}
         {% endfor %}
            
        </tr>
        {% endfor %}
    </table>
    
</div>

  {% endfor %}
 
 
<p style="clear: left;">&nbsp;</p>


<div style="clear: both;" />


{% comment %}

{% endcomment %}

{% endblock %}

esphealth/ESP/templates/ui/unmapped_labs.html
{% extends 'base.html' %}


{% block extrastyle %}
    <style type="text/css">
    table {
        border-width: thin;
        border-spacing: 0;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: white;
    }
    table th {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    table td {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    </style>
{% endblock %}

{% block content %}

<p>
    Searching lab native names for these strings:
    <table>
    <tr> <td>
        {% for s in search_strings %}
          {{ s }} <BR>
	        {% if forloop.counter|divisibleby:"10" %} 
	        </td>
	          {% if not forloop.last %}
	            <td>
	            {% endif %}
	        {% endif %}
        {% endfor %}
    </tr> 
    </table>
</p>


<form method="POST" action="{% url ignore_code_set %}" >
	<p>
	<table>
	    <tr>
		<th />
		<th>Native Name</th>
		<th>Native Code</th>
		<th>Lab Record Count</th>
		{% if user.is_staff %}
		<th></th>
		{% endif %}
	    </tr>
	    {% for item in unmapped %}
	    <tr>
		<td><input type="checkbox" name="codes" value="{{ item.native_code }}" id="id_codes_{{ forloop.counter }}">
		<td>{{ item.native_name }}</td>
		<td>{{ item.native_code }}</td>
		<td>{{ item.count }}</td>
		{% if user.is_staff %}
		<td><a href="{% url map_native_code item.native_code %}">map</a></td>
		{% endif %}
	    </tr>
	    {% endfor %}
	</table>
	</p>
	<p>
		<input type="submit" name="submit" value="Ignore Selected Codes" />
	</p>
</form>


{% endblock %}